---@meta

---@class SMODS.GameObject: Object 
---@field log_interval? number
---@field mod? table Mod this object is created by. 
---@field registered? boolean
---@field obj_table? table Table of objects registered to this class. 
---@field obj_buffer? table Array of keys to all objects registered to this class. 
---@field dependencies? table Array of mod IDs. Object will fail to register if any specified mods cannot load. 
---@field subclasses? table Array of child classes. 
---@field super? table Parent class. 
---@field key? string Unique string to reference this object. 
---@field class_prefix? boolean|string All objects created with this class will have their key prefixed with this string. 
---@field prefix_config? boolean|table Controls how prefixes are applied. By default, class_prefix and mod_prefix are applied to all registered objects. 
---@field required_params? table Array of parameters required for objects created by this class. 
---@field set? string Important for objects wanting to follow vanilla logic that depends on `set`. For classes, this is used for logging purposes. 
---@field no_collection? boolean Sets whether the object shows up in collections. ---@overload fun(self: SMODS.GameObject): SMODS.GameObject
---@field config? table Cards/Objects representing your center will copy default values from `config` into it's `ability` table. Custom values can be stored within `extra`. 
---@field __call? fun(self: table|SMODS.GameObject, o: table|SMODS.GameObject): SMODS.GameObject
---@field extend? fun(self: table|SMODS.GameObject, o: table|SMODS.GameObject): table Primary method of creating a class. 
---@field check_duplicate_register? fun(self: table|SMODS.GameObject): nil|boolean?Ensures objects already registered will not register. 
---@field check_duplicate_key? fun(self: table|SMODS.GameObject): nil|boolean?Ensures objects with duplicate keys will not register. Checked on __call but not take_ownerhsip. For take_ownership, the key must exist. 
---@field register? fun(self: table|SMODS.GameObject) Registers the object. 
---@field check_dependencies? fun(self: table|SMODS.GameObject): nil|boolean?Returns true if there's no failed dependencies, else false
---@field process_loc_text? fun(self: table|SMODS.GameObject) Called during `inject_class`. Handles injecting loc_text. 
---@field send_to_subclasses? fun(self: table|SMODS.GameObject, ...: any) Starting from this class, recusively searches for functions with the given key on all subordinate classes and run all found functions with the given arguments. 
---@field pre_inject_class? fun(self: table|SMODS.GameObject) Called before `inject_class`. Injects and manages class information before object injection. 
---@field post_inject_class? fun(self: table|SMODS.GameObject) Called after `inject_class`. Injects and manages class information after object injection. 
---@field inject_class? fun(self: table|SMODS.GameObject) Inject all direct instances of `o` of the class by calling `o:inject`. Also injects anything necessary for the class itself. Only called if class has defined both `obj_table` and `obj_buffer`. 
---@field inject? fun(self: table|SMODS.GameObject, i?: number) Called during `inject_class`. Injects the object into the game. 
---@field take_ownership? fun(self: table|SMODS.GameObject, key: string, obj: table, silent?: boolean): nil|SMODS.GameObject Takes control of vanilla objects. Child class must have get_obj for this to function
---@field get_obj? fun(self: table|SMODS.GameObject, key: string): table|nil Returns an object if one matches the `key`. 
---@field obj_list? fun(self: table|SMODS.GameObject, reversed: boolean): table Returns an object if one matches the `key`. 
---@overload fun(o: table|SMODS.GameObject): SMODS.GameObject
SMODS.GameObject = setmetatable({})

